modLoader="javafml"
loaderVersion="${forge_loader_version_range}"
license="${license}"
issueTrackerURL="${issue_tracker}"

[[mods]]
    modId="${mod_id}"
    version="${forge_mod_version}"
    displayName="${mod_name}"
    updateJSONURL="https://raw.githubusercontent.com/wendall911/SimpleTextOverlay/${mod_update_branch}/files/forge/updates.json"
    displayURL="${mod_url}"
    authors="${mod_author}"
    credits="${mod_credits}"
    logoFile="logo.png"
    itemIcon="minecraft:compass"
    description='''${mod_description}'''
[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${forge_mc_version_range}"
    ordering="NONE"
    side="BOTH"
