# Gradle
org.gradle.jvmargs=-Xmx3G

# Project
version=5.2.1.15
last_mod_version=5.2.1.14

# Common
minecraft_version=1.21.8
mixin_version=0.8.5
mixin_extras_version=0.3.5
whitenoise_version=1.0.0
whitenoise_range=[1.0.0,2.0.0)
java_version=21

# Parchment
# https://parchmentmc.org/docs/getting-started
mappings_version=2025.07.20

# NeoForge
# https://projects.neoforged.net/neoforged/neoforge
neoforge_version=21.8.46
neoforge_loader_version_range=[4,)
neoforge_mc_version_range=[1.21.2, 1.22)
# https://projects.neoforged.net/neoforged/neoform
neo_form_version=1.21.8-20250717.133445

# Fabric
# https://fabricmc.net/develop/
fabric_version=0.133.4+1.21.8
fabric_loader_version=0.17.2
fabric_loader_min_version=>=0.15
fabric_mc_version_range=["1.21.8","1.21.9"]
# https://www.curseforge.com/minecraft/mc-mods/modmenu/files/all
mod_menu_version=15.0.0

# Other mods
serene_seasons_neoforge_version=6812965
serene_seasons_fabric_version=6812964
glitch_core_neoforge_version=6812823
glitch_core_fabric_version=6812822
ecliptic_neoforge_version=??????
fabric_seasons_version=???
cardinal_components_version=7.0.0-beta.1

# Mod options
mod_id=simpletextoverlay
mod_name=SimpleTextOverlay
mod_author=wendall911
mod_credits=DaftPVF, bspkrs, Lunatrius, ashar42
license=MIT
issue_tracker=https://github.com/wendall911/SimpleTextOverlay/issues
mod_description=Display extra information on top of your in-game screen.
mod_url=https://github.com/wendall911/SimpleTextOverlay
mod_update_branch=1.21

# CurseForge/Modrinth Options
release_type=release
release_versions=1.21.8
