# Gradle
org.gradle.jvmargs=-Xmx3G

# Project
version=5.2.2.0
last_mod_version=5.2.1.9

# Common
minecraft_version=1.18.2
minecraft_short_version=1.18
java_version=17
whitenoise_version=1.0.0
whitenoise_range=[1.0.0, 2.0.0)

# Parchment
# https://parchmentmc.org/docs/getting-started
mappings_version=2022.11.06

# Forge
# https://files.minecraftforge.net/net/minecraftforge/forge/
forge_version=40.3.11
forge_version_range=[40,)
forge_mc_version_range=[1.18.2,1.18.3)

# Fabric
# https://fabricmc.net/develop/
fabric_version=0.77.0+1.18.2
fabric_mc_version_range=1.18.2
fabric_loader_version=0.17.2
fabric_loader_min_version=>=0.14
# https://www.curseforge.com/minecraft/mc-mods/modmenu/files/all
mod_menu_version=3.2.5
# https://www.curseforge.com/minecraft/mc-mods/cardinal-components-api/files/all
cardinal_components_version=4.2.0

# Other mods
serene_seasons_forge_version=3693807
fabric_seasons_version=3779369

# Mod options
mod_id=simpletextoverlay
mod_name=SimpleTextOverlay
mod_author=wendall911
mod_credits=DaftPVF, bspkrs, Lunatrius, ashar42
license=MIT
issue_tracker=https://github.com/wendall911/SimpleTextOverlay/issues
mod_description=Display extra information on top of your in-game screen.
mod_update_branch=1.18.2

# CurseForge/Modrinth Options
release_type=release
release_versions=1.18.2
