modLoader="javafml"
loaderVersion="[1,)"
license="${license}"
issueTrackerURL="${issue_tracker}"

[[mods]]
    modId="${mod_id}"
    version="${neoforge_mod_version}"
    displayName="${mod_name}"
    updateJSONURL="https://raw.githubusercontent.com/wendall911/SimpleTextOverlay/${mod_update_branch}/files/updates.json"
    displayURL="${mod_url}"
    authors="${mod_author}"
    credits="${mod_credits}"
    logoFile="logo.png"
    itemIcon="minecraft:compass"
    description='''${mod_description}'''
[[mixins]]
    config = "${mod_id}.mixins.json"
[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="${neoforge_loader_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${neoforge_mc_version_range}"
    ordering="NONE"
    side="BOTH"
